### ISSUE TITLE
Can't install couchbase fot ubuntu 18.04LTS

### ISSUE THREAD

**Issue by iuria21** [couchbase/docs-sdk-c#18]
Hi, I'm trying installing couchbase as you say:
```
# Install Couchbase's GPG key
sudo wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
# Adding Ubuntu 18.04 LTS repo to apt/sources.list
echo "deb http://packages.couchbase.com/ubuntu bionic bionic/main" | sudo tee /etc/apt/sources.list.d/couchbase.list
# To install or upgrade packages
sudo apt-get update
sudo apt-get install libcouchbase-dev libcouchbase2-bin build-essential
```
but It's not installing... Please help me, I don't know what to do and I need it!

**Comment by RichardSmedley** [comment]
At what stage is it failing, and what are the messages, @basque21 
[Please note you'll get more eyes on an issue like this on the Couchbase Forum - https://forums.couchbase.com ]

**Comment by iuria21** [comment]
I managed to install it (not sure how, trying all the answers in that forum), I forgot to close the issue; sorry and thanks

**Comment by RichardSmedley** [comment]
No problem, @basque21 
(I've been away, so missed the issue when you raised it - I'm glad you got it installed :) )
