### ISSUE TITLE
Correction required in document

### ISSUE THREAD

**Issue by ajay143444** [couchbase/docs-sdk-c#39]
in the Using Extended Attributes paragraph, the below line require correction.
'In order to specify that a subdocument operation should be performed on an extended rather than a regular attribute, an xattr flag should be set to true, by the calling application.

'performed on an extended rather' should be changed to 'performed on an extended attribute rather'

**Comment by RichardSmedley** [comment]
I think it makes sense the way it is, but I'll canvas wider opinion - if there's any doubt, then we'll change in order to clarify.

**Comment by RichardSmedley** [comment]
Hi Ajay,
Thanks for the suggestion,
but everyone canvassed is happy with the clarity of the current wording.
